[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
fuzz = { runs = 256, seed = "0x5eed" }
invariant = { runs = 128, depth = 32, fail_on_revert = false }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
